services:
  mysql:
    image: 'mysql:latest'
    container_name: binaa-mysql
    environment:
      - 'MYSQL_DATABASE=binaa_center'
      - 'MYSQL_ROOT_PASSWORD=root'
    ports:
      - '3306'
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    # Add these for development
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake

volumes:
  mysql_data:
    name: binaa-mysql-data

networks:
  default:
    name: binaa-network