name: Build, Push, and Deploy Java Docker Image

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build the project using Maven
        run: mvn clean package -DskipTests

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t yassingamalz/binaa-center-backend:latest .
          docker push yassingamalz/binaa-center-backend:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push  # Only runs after the build_and_push job is complete

    steps:
      - name: SSH into Oracle Instance and deploy the backend service
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.ORACLE_IP }}
          username: ${{ secrets.ORACLE_USERNAME }}
          key: ${{ secrets.ORACLE_SSH_KEY }}
          script: |
            docker pull yassingamalz/binaa-center-backend:latest
            docker stop binaa-center-backend || true
            docker rm binaa-center-backend || true
            docker run -d \
              -p 8080:8080 \
              --name binaa-center-backend \
              --network binaa-network \
              yassingamalz/binaa-center-backend:latest
